### PR TITLE
code push for fe-training-exercise-harsh

### PR DESCRIPTION
**Pull request by htRightPoint**

### CODE REVIEW

**Comment by Lalit-gour1** [comment]
@htRightPoint Please add screenshot of result of your code

**Comment by htRightPoint** [comment]
Desktop design and its theme: -

2024-07-16_14h46_00
2024-07-16_14h46_12

Mobile design: -
2024-07-16_14h46_50
2024-07-16_14h47_00



> @htRightPoint Please add screenshot of result of your code

**Comment by Lalit-gour1** [comment]
@htRightPoint  Please resolve your conflict

**Review by mathrik — APPROVED** [review]
This looks good to me. It performs well in the browser and the CSS looks clean. I'll merge once you've resolved the conflicts.

**Pull request closed without merging**
