### PR TITLE
code push for fifty-fifty teaser component

### PR DESCRIPTION
**Pull request by htRightPoint**
Expected design for Desktop/Tab: -
fifty-fifty-teaser-desktop

Expected design for Mobile: -
fifty-fifty-teaser-mobile

### CODE REVIEW

**Comment by Lalit-gour1** [comment]
@htRightPoint will there be no padding from left and right in title, pretitle  for mobile.
Cc:- @jvaishnavrp

**Review by mathrik — COMMENTED** [review]
This looks good. The CSS is solid and looks mostly good in the browser. Only thing I would change is that you have nice padding on desktop/table but mobile widths bleed into the browser chrome. I would expect the same padding to still be there on mobile.

**Comment by htRightPoint** [comment]
@mathrik @Lalit-gour1 because there was no padding given in my design for mobile, that's why I hadn't added padding earlier, but now I have added it. Thanks!
cc: @jvaishnavrp

**Comment by mathrik** [comment]
> @mathrik @Lalit-gour1 because there was no padding given in my design for mobile, that's why I hadn't added padding earlier, but now I have added it. Thanks! cc: @jvaishnavrp

FIgured it was something like that. Looks good to me now.

**Comment by mathrik** [comment]
Looks like you have some merge conflicts that need to be resolved.

**Pull request merged**
